#ifndef TREND_DB_H_ 
#define TREND_DB_H_

 #define tDB_TREND_VENTIL_HOUR						{0,23,NONE,0x0000}
    #define tDB_TREND_VENTIL_MIN						{0,59,NONE,0x0000}
    #define tDB_TREND_AVG_VTI							{0,65530,NONE,0x0000}
    #define tDB_TREND_SIG_VTI							{0,NONE,NONE,0x0000}	   
    #define tDB_TREND_AVG_VTE							{0,65530,NONE,0x0000}
    #define tDB_TREND_SIG_VTE							{0,NONE,NONE,0x0000}
    #define tDB_TREND_AVG_VM							{0,9990,NONE,0x0000}
    #define tDB_TREND_SIG_VM							{0,NONE,NONE,0x0000}
    #define tDB_TREND_AVG_FR							{0,990,NONE,0x0000}
    #define tDB_TREND_SIG_FR							{0,NONE,NONE,0x0000}
    #define tDB_TREND_LEAK_MODE							{0,NONE,NONE,0x0000}
    #define tDB_TREND_AVG_LEAK							{0,15000,NONE,0x0000}
    #define tDB_TREND_SIG_LEAK							{0,NONE,NONE,0x0000}
    #define tDB_TREND_AVG_PI							{0,9900,NONE,0x0000}
    #define tDB_TREND_SIG_PI							{0,NONE,NONE,0x0000}
    #define tDB_TREND_IA								{0,999,NONE,0x0000}
    #define tDB_TREND_APNEA								{0,999,NONE,0x0000}
    #define tDB_TREND_PERCENT_CONTROLLED				{0,100,NONE,0x0000}
    #define tDB_TREND_PERCENT_TRIGGERED					{0,100,NONE,0x0000}
    #define tDB_TREND_SAVE_RTC_DAY						{1,31,NONE,0x0000}
    #define tDB_TREND_SAVE_RTC_MONTH					{1,12,NONE,0x0000}
    #define tDB_TREND_SAVE_RTC_YEAR						{4,99,NONE,0x0000}
    #define tDB_TREND_SAVE_PC_HOUR						{0,24,NONE,0x0000}
    #define tDB_TREND_SAVE_PC_MIN						{0,59,NONE,0x0000}
    #define tDB_TREND_NB_APNEA							{0,65535,NONE,0x0000}
    #define tDB_TREND_APNEA_TIME						{0,65535,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_COUNTER_MSB					{0,NONE,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_COUNTER_LSB					{0,65535,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_TRIGERRED_MSB			{0,NONE,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_TRIGERRED_LSB			{0,65535,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_CONTROLLED_MSB			{0,NONE,NONE,0x0000}
    #define tDB_TREND_NB_CYCLE_CONTROLLED_LSB			{0,65535,NONE,0x0000}
    #define tDB_TREND_VENTIL_REPORT_UPD					{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_VENTIL_HOUR 					{0,23,NONE,0x0000}
    #define tDB_TREND_IHM_VENTIL_MIN					{0,59,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_VTI						{0,65530,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_VTI						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_VTE						{0,65530,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_VTE						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_VM						{0,9990,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_VM						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_FR						{0,990,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_FR						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_LEAK_MODE						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_LEAK						{0,15000,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_LEAK						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_AVG_PI						{0,9900,NONE,0x0000}
    #define tDB_TREND_IHM_SIG_PI						{0,NONE,NONE,0x0000}
    #define tDB_TREND_IHM_IA							{0,999,NONE,0x0000}
    #define tDB_TREND_IHM_APNEA							{0,999,NONE,0x0000}
    #define tDB_TREND_IHM_PERCENT_CONTROLLED			{0,100,NONE,0x0000}
    #define tDB_TREND_IHM_PERCENT_TRIGGERED				{0,100,NONE,0x0000}
    #define tDB_TREND_IHM_SAVE_RTC_DAY					{0,31,NONE,0x0000}
    #define tDB_TREND_IHM_SAVE_RTC_MONTH				{0,12,NONE,0x0000}
    #define tDB_TREND_IHM_SAVE_RTC_YEAR					{0,2099,NONE,0x0000}


typedef enum

{

   DB_TREND_VENTIL_HOUR = 0,

   DB_TREND_VENTIL_MIN,

   DB_TREND_AVG_VTI,

   DB_TREND_AVG_VTE,

   DB_TREND_AVG_VM,

   DB_TREND_AVG_FR,

   DB_TREND_LEAK_MODE,      

   DB_TREND_AVG_LEAK,

   DB_TREND_AVG_PI,

   DB_TREND_IA,

   DB_TREND_APNEA,

   DB_TREND_PERCENT_CONTROLLED,

   DB_TREND_PERCENT_TRIGGERED,

   DB_TREND_SAVE_RTC_DAY,

   DB_TREND_SAVE_RTC_MONTH,

   DB_TREND_SAVE_RTC_YEAR,

   DB_TREND_SAVE_PC_HOUR,

   DB_TREND_SAVE_PC_MIN,

   DB_TREND_NB_APNEA,

   DB_TREND_APNEA_TIME,

   DB_TREND_NB_CYCLE_COUNTER_MSB,

   DB_TREND_NB_CYCLE_COUNTER_LSB,

   DB_TREND_NB_CYCLE_TRIGERRED_MSB,

   DB_TREND_NB_CYCLE_TRIGERRED_LSB,

   DB_TREND_NB_CYCLE_CONTROLLED_MSB,

   DB_TREND_NB_CYCLE_CONTROLLED_LSB,

   DB_TREND_VENTIL_REPORT_UPD,

   DB_TREND_IHM_VENTIL_HOUR,

   DB_TREND_IHM_VENTIL_MIN,

   DB_TREND_IHM_AVG_VTI,

   DB_TREND_IHM_AVG_VTE,

   DB_TREND_IHM_AVG_VM,

   DB_TREND_IHM_AVG_FR,

   DB_TREND_IHM_LEAK_MODE,      

   DB_TREND_IHM_AVG_LEAK,

   DB_TREND_IHM_AVG_PI,

   DB_TREND_IHM_IA,

   DB_TREND_IHM_APNEA,

   DB_TREND_IHM_PERCENT_CONTROLLED,

   DB_TREND_IHM_PERCENT_TRIGGERED,

   DB_TREND_IHM_SAVE_RTC_DAY,

   DB_TREND_IHM_SAVE_RTC_MONTH,

   DB_TREND_IHM_SAVE_RTC_YEAR,

   end_of_db_trend_table

} e_DB_Trend;



#endif

