#ifndef VERSION_DB_H_ 
#define VERSION_DB_H_
#define tSERIAL_NUMBER_1							{NONE,NONE,NONE,0x0000} // 00
#define tSERIAL_NUMBER_2							{NONE,NONE,NONE,0x0000} // 00
#define tSERIAL_NUMBER_3							{NONE,NONE,NONE,0x0000} // 00
#define tSERIAL_NUMBER_4							{NONE,NONE,NONE,0x0000} // 00
#define tSERIAL_NUMBER_5							{NONE,NONE,NONE,0x0000} // 00
#define tSERIAL_NUMBER_6							{NONE,NONE,NONE,0x0000} // 00


typedef enum
{
	VERSION_NUMBER_0 = 0,
	VERSION_NUMBER_1,
	VERSION_NUMBER_2,
	VERSION_NUMBER_3,
	SERIAL_NUMBER_1,
	SERIAL_NUMBER_2,
	SERIAL_NUMBER_3,
	SERIAL_NUMBER_4,
	SERIAL_NUMBER_5,
	SERIAL_NUMBER_6,
	end_of_db_version_table
} e_DB_VERSION;


#endif
